export const AUTHENTICATION_GETDATA_REQUEST = 'AUTHENTICATION_GETDATA_REQUEST';
export const AUTHENTICATION_GETDATA_SUCCESS = 'AUTHENTICATION_GETDATA_SUCCESS';
export const AUTHENTICATION_GETDATA_FAILURE = 'AUTHENTICATION_GETDATA_FAILURE';
export const AUTHENTICATION_SET_FETCHED_ROLE = 'AUTHENTICATION_SET_FETCHED_ROLE';
export const AUTHENTICATION_SET_DEFAULT_ROLE = 'AUTHENTICATION_SET_DEFAULT_ROLE';
