export const USER_LOGIN = 'USER_LOGIN'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const USER_SIGNUP = 'USER_SIGNUP'
export const SIGNUP_SUCCEEDED = 'SIGNUP_SUCCEEDED'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
