export const ADD_USER = 'ADD_USER';
export const SEARCH_USER = 'SEARCH_USER';
export const USER_LOGOFF = 'USER_LOGOFF';
export const ERROR_REDIRECT = 'ERROR_REDIRECT';
export const SIGNIN_SAVE_DATA_REQUEST = 'SIGNIN_SAVE_DATA_REQUEST';
export const SIGNIN_SAVE_DATA_SUCCESS = 'SIGNIN_SAVE_DATA_SUCCESS';
export const LOGIN_SEARCH_DATA_REQUEST = 'LOGIN_SEARCH_DATA_REQUEST';
export const LOGIN_SEARCH_DATA_SUCCESS = 'LOGIN_SEARCH_DATA_SUCCESS';