export default {
  SEND_FULLNAME: 'SEND_FULLNAME',
  SEND_CONTRAINDICATIONS: 'SEND_CONTRAINDICATIONS',
  WAIT_SEND_DATA: 'WAIT_SEND_DATA',
  DELETE_WAIT_SEND_DATA: 'DELETE_WAIT_SEND_DATA',
  SEND_DATA_ERROR: 'SEND_DATA_ERROR',
  GIVE_PERSONAL_DATA: 'GIVE_PERSONAL_DATA'
}
