// export default {
//   SEND_FULLNAME: 'SEND_FULLNAME',
//   SEND_CONTRAINDICATIONS: 'SEND_CONTRAINDICATIONS',
//   WAIT_SEND_DATA: 'WAIT_SEND_DATA',
//   DELETE_WAIT_SEND_DATA: 'DELETE_WAIT_SEND_DATA',
//   SEND_DATA_ERROR: 'SEND_DATA_ERROR',
//   GIVE_PERSONAL_DATA: 'GIVE_PERSONAL_DATA'
// }

export const FORM_REQUEST = 'FORM_REQUEST';
export const FORM_SUCCESS = 'FORM_SUCCESS';
export const ACTION_FAILURE = 'ACTION_FAILURE';
export const FORM_SIZES_REQUEST = 'FORM_SIZES_REQUEST';
export const FORM_SIZES_SUCCESS = 'FORM_SIZES_SUCCESS';
export const FORM_AIMS_REQUEST = 'FORM_AIMS_REQUEST';
export const FORM_AIMS_SUCCESS = 'FORM_AIMS_SUCCESS';
export const FORM_CONTRA_REQUEST = 'FORM_CONTRA_REQUEST';
export const FORM_CONTRA_SUCCESS = 'FORM_CONTRA_SUCCESS';
export const PAGE_ABOUTUS_REQUEST = 'PAGE_ABOUTUS_REQUEST';
export const PAGE_ABOUTUS_SUCCESS = 'PAGE_ABOUTUS_SUCCESS';
export const WAIT_SEND_DATA = 'WAIT_SEND_DATA';
export const DELETE_WAIT_SEND_DATA = 'DELETE_WAIT_SEND_DATA';
